#!/bin/bash
# Generate Falcosidekick configuration from .env settings
#
# Usage: ./scripts/generate-sidekick-config.sh
#
# The output is regenerated on every 'make install-alerting'. Do not hand-edit
# it — put advanced outputs in alerting/config/custom-outputs.yaml, which is
# appended verbatim and never overwritten.

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
OUTPUT="${PROJECT_ROOT}/alerting/config/config.yaml"
OVERLAY="${PROJECT_ROOT}/alerting/config/custom-outputs.yaml"

# Load environment
MTLS_ENABLED="${MTLS_ENABLED:-false}"
STACK="${STACK:-vm}"

# Determine Loki endpoint based on stack
if [ "$STACK" = "vm" ]; then
    LOKI_HOSTPORT="http://sib-victorialogs:9428/insert"
else
    LOKI_HOSTPORT="http://sib-loki:3100"
fi

# Emit "key: value" only when the value is non-empty, so unconfigured fields are
# omitted rather than written as empty strings.
emit() {
    [ -n "$2" ] && echo "  $1: \"$2\""
    return 0
}

# Quote a scalar for the generated YAML. Output destinations are often URLs or
# secrets, so treating their contents as YAML syntax is both fragile and unsafe.
yaml_quote() {
    local value="$1"
    value=${value//\\/\\\\}
    value=${value//\"/\\\"}
    printf '"%s"' "$value"
}

# Generate config
{
    echo "# Falcosidekick Configuration"
    echo "#"
    echo "# AUTO-GENERATED by scripts/generate-sidekick-config.sh — DO NOT EDIT."
    echo "# Regenerated on every 'make install-alerting'; hand edits are lost."
    echo "# Configure outputs in .env, or add advanced outputs to"
    echo "# alerting/config/custom-outputs.yaml (appended below, never overwritten)."
    echo "#"
    echo "# mTLS: ${MTLS_ENABLED}"
    echo "debug: ${SIDEKICK_DEBUG:-false}"
    echo "minimumpriority: \"${SIDEKICK_MINIMUM_PRIORITY:-notice}\""
    echo ""
    echo "# Loki output - VictoriaLogs is Loki-compatible for ingestion"
    echo "loki:"
    echo "  hostport: \"${LOKI_HOSTPORT}\""

    if [ -n "${SLACK_WEBHOOK_URL:-}" ]; then
        echo ""
        echo "slack:"
        emit webhookurl "${SLACK_WEBHOOK_URL}"
        emit channel "${SLACK_CHANNEL:-}"
        emit minimumpriority "${SLACK_MINIMUM_PRIORITY:-}"
    fi

    if [ -n "${DISCORD_WEBHOOK_URL:-}" ]; then
        echo ""
        echo "discord:"
        emit webhookurl "${DISCORD_WEBHOOK_URL}"
        emit minimumpriority "${DISCORD_MINIMUM_PRIORITY:-}"
    fi

    if [ -n "${PAGERDUTY_ROUTING_KEY:-}" ]; then
        echo ""
        echo "pagerduty:"
        emit routingkey "${PAGERDUTY_ROUTING_KEY}"
        emit minimumpriority "${PAGERDUTY_MINIMUM_PRIORITY:-critical}"
    fi

    if [ -n "${OPSGENIE_API_KEY:-}" ]; then
        echo ""
        echo "opsgenie:"
        emit apikey "${OPSGENIE_API_KEY}"
        emit region "${OPSGENIE_REGION:-us}"
        emit minimumpriority "${OPSGENIE_MINIMUM_PRIORITY:-}"
    fi

    if [ -n "${TEAMS_WEBHOOK_URL:-}" ]; then
        echo ""
        echo "teams:"
        emit webhookurl "${TEAMS_WEBHOOK_URL}"
        emit minimumpriority "${TEAMS_MINIMUM_PRIORITY:-}"
    fi

    if [ -n "${ELASTICSEARCH_HOST_PORT:-}" ]; then
        echo ""
        echo "elasticsearch:"
        emit hostport "${ELASTICSEARCH_HOST_PORT}"
        emit index "${ELASTICSEARCH_INDEX:-falco}"
    fi

    if [ -n "${WEBHOOK_ADDRESS:-}" ]; then
        echo ""
        echo "webhook:"
        printf '  address: %s\n' "$(yaml_quote "${WEBHOOK_ADDRESS}")"
        if [ -n "${WEBHOOK_HEADER_NAME:-}" ] || [ -n "${WEBHOOK_HEADER_VALUE:-}" ]; then
            if [ -z "${WEBHOOK_HEADER_NAME:-}" ] || [ -z "${WEBHOOK_HEADER_VALUE:-}" ]; then
                echo "Both WEBHOOK_HEADER_NAME and WEBHOOK_HEADER_VALUE must be set" >&2
                exit 1
            fi
            if [[ ! "${WEBHOOK_HEADER_NAME}" =~ ^[A-Za-z0-9-]+$ ]]; then
                echo "WEBHOOK_HEADER_NAME contains invalid characters" >&2
                exit 1
            fi
            echo "  customHeaders:"
            printf '    %s: %s\n' "${WEBHOOK_HEADER_NAME}" "$(yaml_quote "${WEBHOOK_HEADER_VALUE}")"
        fi
        printf '  minimumpriority: %s\n' "$(yaml_quote "${WEBHOOK_MINIMUM_PRIORITY:-warning}")"
    fi

    if [ "$MTLS_ENABLED" = "true" ]; then
        echo ""
        echo "# mTLS TLS Server Configuration"
        echo "tlsserver:"
        echo "  deploy: true"
        echo "  certfile: /certs/server/server.crt"
        echo "  keyfile: /certs/server/server.key"
        echo "  mutualtls: true"
        echo "  cacertfile: /certs/ca/ca.crt"
    fi

    if [ -f "$OVERLAY" ]; then
        echo ""
        echo "# ---- appended from alerting/config/custom-outputs.yaml ----"
        cat "$OVERLAY"
    fi
} > "$OUTPUT"
chmod 600 "$OUTPUT"

CONFIGURED=""
for pair in "SLACK_WEBHOOK_URL:Slack" "DISCORD_WEBHOOK_URL:Discord" \
            "PAGERDUTY_ROUTING_KEY:PagerDuty" "OPSGENIE_API_KEY:Opsgenie" \
            "TEAMS_WEBHOOK_URL:Teams" "ELASTICSEARCH_HOST_PORT:Elasticsearch" \
            "WEBHOOK_ADDRESS:Webhook"; do
    var="${pair%%:*}"
    label="${pair##*:}"
    if [ -n "${!var:-}" ]; then
        CONFIGURED="${CONFIGURED} ${label}"
    fi
done

if [ "$MTLS_ENABLED" = "true" ]; then
    echo "Generated Falcosidekick config with mTLS enabled"
else
    echo "Generated Falcosidekick config (HTTP mode)"
fi
[ -n "$CONFIGURED" ] && echo "  Outputs enabled:${CONFIGURED}"
[ -f "$OVERLAY" ] && echo "  Appended custom-outputs.yaml"
exit 0
