# VM Collectors Stack - vmagent + node_exporter
# Lightweight alternative to Alloy for VictoriaMetrics ecosystem
# Deploy on remote hosts to ship logs/metrics to SIB server
#
# Usage:
#   SIB_SERVER=192.168.1.196 HOSTNAME=$(hostname) docker compose -f compose.yaml up -d
#   To skip node-exporter (if already running): add --scale node-exporter=0

services:
  vmagent:
    image: victoriametrics/vmagent:latest
    container_name: sib-vmagent
    hostname: ${HOSTNAME:-collector}
    restart: unless-stopped
    command:
      - "-promscrape.config=/etc/vmagent/config.yml"
      - "-remoteWrite.url=http://${SIB_SERVER:-localhost}:8428/api/v1/write"
      - "-remoteWrite.label=host=${HOSTNAME:-collector}"
    volumes:
      - ./config/vmagent.yml:/etc/vmagent/config.yml:ro
      - vmagent-data:/vmagent-data
    network_mode: host

  node-exporter:
    image: prom/node-exporter:latest
    container_name: sib-node-exporter
    hostname: ${HOSTNAME:-collector}
    restart: unless-stopped
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/host/root'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/host/root:ro
    network_mode: host
    pid: host

  vector:
    image: timberio/vector:latest-alpine
    container_name: sib-vector
    hostname: ${HOSTNAME:-collector}
    restart: unless-stopped
    volumes:
      - ./config/vector.toml:/etc/vector/vector.toml:ro
      - /var/log:/var/log:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - vector-data:/var/lib/vector
    environment:
      - HOSTNAME=${HOSTNAME:-collector}
      - SIB_SERVER=${SIB_SERVER:-localhost}
      - VECTOR_CONFIG=/etc/vector/vector.toml
    network_mode: host

volumes:
  vmagent-data:
  vector-data:
